# See: https://prettier.io/docs/configuration

overrides:
  - files:
      - "*.html"
    options:
      parser: go-template
  - files:
      - "*.toml"
    options:
      parser: toml
plugins:
  - prettier-plugin-go-template
  - prettier-plugin-toml
printWidth: 120
