[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "3.11.*"

[tool.poetry.group.dev.dependencies]
codespell = "2.4.3"
yamllint = "1.38.0"

# The dependencies in this group are installed using pipx instead of Poetry. It is necessary to use a poetry section in
# order to get Dependabot updates of the dependencies.
[tool.poetry.group.pipx.dependencies]
poetry = "2.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
